name: CI

on: [push, pull_request]

permissions:
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - run: bun ci

            - run: bun run check:assets

            - run: bun run lint

            - run: bun run lint:style

            - run: bun run prettier:check

            - run: bun run test

            - run: bun run tsc

            - run: bun run mainnet && bun run build

    package:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packages/boltz-swaps
        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun ci
              working-directory: .

            - run: bun run lint

            - run: bun run prettier:check

            - run: bun run test

            - run: bun run tsc

            - run: bun run build
